//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEC2ON.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SEC2ON.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j93h8yfahdiudog.
        /// </summary>
        internal static string dropboxAppKey {
            get {
                return ResourceManager.GetString("dropboxAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 92f0rcs8ynwu4cm.
        /// </summary>
        internal static string dropboxAppSecret {
            get {
                return ResourceManager.GetString("dropboxAppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sdb_backup.
        /// </summary>
        internal static string ExtensionBackup {
            get {
                return ResourceManager.GetString("ExtensionBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~synctemp.tmp.
        /// </summary>
        internal static string TempDBFile {
            get {
                return ResourceManager.GetString("TempDBFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180000.
        /// </summary>
        internal static string timeOutPasswordHandler {
            get {
                return ResourceManager.GetString("timeOutPasswordHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string timeToDeleteClipboardSeconds {
            get {
                return ResourceManager.GetString("timeToDeleteClipboardSeconds", resourceCulture);
            }
        }
    }
}
